# 访问端口
server:
  port: 8088

# 数据库数据源
spring:
#加载静态页面路径
  thymeleaf:
    prefix: classpath:static/html/
    suffix: .html

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/java_test?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
#    username: root
#    password: 123456
#
## 日志配置
#logging:
#  file:
#    name: log/out.log
#  level:
#    root: info
#    com:
#      du:
#        TeseProject: debug
#
#mybatis:
#  mapper-locations: classpath:mapper/*.xml    # xml文件
#  type-aliases-package: com.du.TestProject.entity  # 别名